//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabZKT.Memory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabZKT.Memory.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOP.
        /// </summary>
        internal static string aopLabel {
            get {
                return ResourceManager.GetString("aopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy napewno chcesz wyczyścić całą pamięć?.
        /// </summary>
        internal static string areYouSureClearTable {
            get {
                return ResourceManager.GetString("areYouSureClearTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tej operacji nie da się cofnąć!.
        /// </summary>
        internal static string areYouSureClearTableTitle {
            get {
                return ResourceManager.GetString("areYouSureClearTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to binarnie.
        /// </summary>
        internal static string binRadioButton {
            get {
                return ResourceManager.GetString("binRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string cancelChoiceButton {
            get {
                return ResourceManager.GetString("cancelChoiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string cancelComplexButton {
            get {
                return ResourceManager.GetString("cancelComplexButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string cancelDataButton {
            get {
                return ResourceManager.GetString("cancelDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string cancelSimpleButton {
            get {
                return ResourceManager.GetString("cancelSimpleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string cellAddressViewGrid {
            get {
                return ResourceManager.GetString("cellAddressViewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawartość.
        /// </summary>
        internal static string cellValueViewGrid {
            get {
                return ResourceManager.GetString("cellValueViewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozkaz rozszerzony.
        /// </summary>
        internal static string choiceComplexButton {
            get {
                return ResourceManager.GetString("choiceComplexButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dana.
        /// </summary>
        internal static string choiceDataButton {
            get {
                return ResourceManager.GetString("choiceDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozkaz prosty.
        /// </summary>
        internal static string choiceSimpleButton {
            get {
                return ResourceManager.GetString("choiceSimpleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść wiersz.
        /// </summary>
        internal static string clearRowButton {
            get {
                return ResourceManager.GetString("clearRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść pamięć.
        /// </summary>
        internal static string clearTableButton {
            get {
                return ResourceManager.GetString("clearTableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozkaz złożony.
        /// </summary>
        internal static string complexInstructionType {
            get {
                return ResourceManager.GetString("complexInstructionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA.
        /// </summary>
        internal static string daLabel {
            get {
                return ResourceManager.GetString("daLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dana.
        /// </summary>
        internal static string dataType {
            get {
                return ResourceManager.GetString("dataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość dziesiętna.
        /// </summary>
        internal static string decimalValue {
            get {
                return ResourceManager.GetString("decimalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dziesiętnie.
        /// </summary>
        internal static string decRadioButton {
            get {
                return ResourceManager.GetString("decRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj komórkę.
        /// </summary>
        internal static string editMemoryButton {
            get {
                return ResourceManager.GetString("editMemoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string field {
            get {
                return ResourceManager.GetString("field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szesnastkowo.
        /// </summary>
        internal static string hexRadioButton {
            get {
                return ResourceManager.GetString("hexRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj pamięć.
        /// </summary>
        internal static string loadTableButton {
            get {
                return ResourceManager.GetString("loadTableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To nie jest poprawny plik pamięci operacyjnej!.
        /// </summary>
        internal static string memLoadError {
            get {
                return ResourceManager.GetString("memLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładowanie pamięci przerwane.
        /// </summary>
        internal static string memLoadErrorTitle {
            get {
                return ResourceManager.GetString("memLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykryto niespójność pliku!.
        /// </summary>
        internal static string memLoadNotValid {
            get {
                return ResourceManager.GetString("memLoadNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja komórki.
        /// </summary>
        internal static string MemSubmitTitle {
            get {
                return ResourceManager.GetString("MemSubmitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamięć Operacyjna.
        /// </summary>
        internal static string MemViewTitle {
            get {
                return ResourceManager.GetString("MemViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonik.
        /// </summary>
        internal static string mnemonicName {
            get {
                return ResourceManager.GetString("mnemonicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string nLabel {
            get {
                return ResourceManager.GetString("nLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        internal static string okComplexButton {
            get {
                return ResourceManager.GetString("okComplexButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        internal static string okDataButton {
            get {
                return ResourceManager.GetString("okDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        internal static string okSimpleButton {
            get {
                return ResourceManager.GetString("okSimpleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP.
        /// </summary>
        internal static string opLabel {
            get {
                return ResourceManager.GetString("opLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ Komórki.
        /// </summary>
        internal static string recordType {
            get {
                return ResourceManager.GetString("recordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz pamięć.
        /// </summary>
        internal static string saveTableButton {
            get {
                return ResourceManager.GetString("saveTableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozkaz prosty.
        /// </summary>
        internal static string simpleInstructionType {
            get {
                return ResourceManager.GetString("simpleInstructionType", resourceCulture);
            }
        }
    }
}
