//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabZSK.StaticClasses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Instructions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Instructions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabZSK.StaticClasses.Instructions", typeof(Instructions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie.
        /// </summary>
        internal static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj do RI.
        /// </summary>
        internal static string ADX {
            get {
                return ResourceManager.GetString("ADX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesunięcie arytmetyczne A w lewo.
        /// </summary>
        internal static string ALA {
            get {
                return ResourceManager.GetString("ALA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesunięcie arytmetyczne A w prawo.
        /// </summary>
        internal static string ARA {
            get {
                return ResourceManager.GetString("ARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skocz jeśli A &lt; 0.
        /// </summary>
        internal static string BAN {
            get {
                return ResourceManager.GetString("BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skocz jeśli nadmiar A.
        /// </summary>
        internal static string BAO {
            get {
                return ResourceManager.GetString("BAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skocz jeśli A &gt; 0.
        /// </summary>
        internal static string BAP {
            get {
                return ResourceManager.GetString("BAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skocz jeśli A = 0.
        /// </summary>
        internal static string BAZ {
            get {
                return ResourceManager.GetString("BAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skok jeśli urządzenie niedostępne.
        /// </summary>
        internal static string BDN {
            get {
                return ResourceManager.GetString("BDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skocz jeśli RI &lt; 0.
        /// </summary>
        internal static string BXN {
            get {
                return ResourceManager.GetString("BXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skocz jeśli RI &gt; 0.
        /// </summary>
        internal static string BXP {
            get {
                return ResourceManager.GetString("BXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skocz jeśli RI = 0.
        /// </summary>
        internal static string BXZ {
            get {
                return ResourceManager.GetString("BXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzupełnienie A do 2.
        /// </summary>
        internal static string CMA {
            get {
                return ResourceManager.GetString("CMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podłącz urządzenie.
        /// </summary>
        internal static string CND {
            get {
                return ResourceManager.GetString("CND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmniejsz modyfikator RI.
        /// </summary>
        internal static string DEX {
            get {
                return ResourceManager.GetString("DEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzielenie.
        /// </summary>
        internal static string DIV {
            get {
                return ResourceManager.GetString("DIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zezwolenie na przerwania.
        /// </summary>
        internal static string ENI {
            get {
                return ResourceManager.GetString("ENI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Różnica symetryczna A i komórki.
        /// </summary>
        internal static string EOR {
            get {
                return ResourceManager.GetString("EOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwiększ modyfikator RI.
        /// </summary>
        internal static string INX {
            get {
                return ResourceManager.GetString("INX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładuj A bezpośrednio.
        /// </summary>
        internal static string LAI {
            get {
                return ResourceManager.GetString("LAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iloczyn logiczny A i komórki.
        /// </summary>
        internal static string LAND {
            get {
                return ResourceManager.GetString("LAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesunięcie cykliczne A w lewo.
        /// </summary>
        internal static string LCA {
            get {
                return ResourceManager.GetString("LCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładuj akumulator A.
        /// </summary>
        internal static string LDA {
            get {
                return ResourceManager.GetString("LDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj status.
        /// </summary>
        internal static string LDS {
            get {
                return ResourceManager.GetString("LDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładuj modyfikator RI.
        /// </summary>
        internal static string LDX {
            get {
                return ResourceManager.GetString("LDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładuj licznik słów WE-WY.
        /// </summary>
        internal static string LIO {
            get {
                return ResourceManager.GetString("LIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesunięcie logiczne A w lewo.
        /// </summary>
        internal static string LLA {
            get {
                return ResourceManager.GetString("LLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesunięcie logiczne A || MQ w lewo.
        /// </summary>
        internal static string LLQ {
            get {
                return ResourceManager.GetString("LLQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negacja logiczna A.
        /// </summary>
        internal static string LNG {
            get {
                return ResourceManager.GetString("LNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma logiczna A i komórki.
        /// </summary>
        internal static string LOR {
            get {
                return ResourceManager.GetString("LOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesunięcie lgoczine A w prawo.
        /// </summary>
        internal static string LRA {
            get {
                return ResourceManager.GetString("LRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przesunięcie logiczne A || MQ w prawo.
        /// </summary>
        internal static string LRQ {
            get {
                return ResourceManager.GetString("LRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładuj RI bezpośrednio.
        /// </summary>
        internal static string LXI {
            get {
                return ResourceManager.GetString("LXI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnożenie.
        /// </summary>
        internal static string MUL {
            get {
                return ResourceManager.GetString("MUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nic nie rób.
        /// </summary>
        internal static string NOP {
            get {
                return ResourceManager.GetString("NOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start operacji WE-WY.
        /// </summary>
        internal static string SIO {
            get {
                return ResourceManager.GetString("SIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skok ze śladem.
        /// </summary>
        internal static string SRJ {
            get {
                return ResourceManager.GetString("SRJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj akumulator A.
        /// </summary>
        internal static string STA {
            get {
                return ResourceManager.GetString("STA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj LR.
        /// </summary>
        internal static string STC {
            get {
                return ResourceManager.GetString("STC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop dynamiczny.
        /// </summary>
        internal static string STP {
            get {
                return ResourceManager.GetString("STP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj rejestr MQ.
        /// </summary>
        internal static string STQ {
            get {
                return ResourceManager.GetString("STQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj modyfikator RI.
        /// </summary>
        internal static string STX {
            get {
                return ResourceManager.GetString("STX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odejmowanie.
        /// </summary>
        internal static string SUB {
            get {
                return ResourceManager.GetString("SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RI = RI - 1 i Skocz jeśli RI &gt; 0.
        /// </summary>
        internal static string TLD {
            get {
                return ResourceManager.GetString("TLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prześlij MQ do A.
        /// </summary>
        internal static string TMQ {
            get {
                return ResourceManager.GetString("TMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prześlij RI do A.
        /// </summary>
        internal static string TXA {
            get {
                return ResourceManager.GetString("TXA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skok bezwarunkowy.
        /// </summary>
        internal static string UNB {
            get {
                return ResourceManager.GetString("UNB", resourceCulture);
            }
        }
    }
}
