//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabZKT.StaticClasses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Operations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Operations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabZKT.StaticClasses.Operations", typeof(Operations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALA            arytmetyczne A w lewo.
        /// </summary>
        internal static string ALA {
            get {
                return ResourceManager.GetString("ALA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARA            arytmetyczne A w prawo.
        /// </summary>
        internal static string ARA {
            get {
                return ResourceManager.GetString("ARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEA            Oblicz adres efektywny.
        /// </summary>
        internal static string CEA {
            get {
                return ResourceManager.GetString("CEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWC            Rozpoczęcie CWC.
        /// </summary>
        internal static string CWC {
            get {
                return ResourceManager.GetString("CWC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END            Koniec mikroprogramu.
        /// </summary>
        internal static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENI            Odblokuj przerwania.
        /// </summary>
        internal static string ENI {
            get {
                return ResourceManager.GetString("ENI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAS            A0 -&gt; ZNAK.
        /// </summary>
        internal static string IAS {
            get {
                return ResourceManager.GetString("IAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IWC            Rozpoczęcie IWC.
        /// </summary>
        internal static string IWC {
            get {
                return ResourceManager.GetString("IWC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCA            cykliczne A w lewo.
        /// </summary>
        internal static string LCA {
            get {
                return ResourceManager.GetString("LCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLA            logiczne A w lewo.
        /// </summary>
        internal static string LLA {
            get {
                return ResourceManager.GetString("LLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLQ            logiczne A i MQ w lewo.
        /// </summary>
        internal static string LLQ {
            get {
                return ResourceManager.GetString("LLQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRA            logiczne A w prawo.
        /// </summary>
        internal static string LRA {
            get {
                return ResourceManager.GetString("LRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRQ            logiczne A i MQ w prawo.
        /// </summary>
        internal static string LRQ {
            get {
                return ResourceManager.GetString("LRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC            OP lub AOP+32 -&gt; RAPS.
        /// </summary>
        internal static string OPC {
            get {
                return ResourceManager.GetString("OPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RRC            Rozpoczęcie RRC.
        /// </summary>
        internal static string RRC {
            get {
                return ResourceManager.GetString("RRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGN            X0 -&gt; ZNAK.
        /// </summary>
        internal static string SGN {
            get {
                return ResourceManager.GetString("SGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHT            Operacja przesunięcia.
        /// </summary>
        internal static string SHT {
            get {
                return ResourceManager.GetString("SHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIND           Adresowanie pośrednie.
        /// </summary>
        internal static string TIND {
            get {
                return ResourceManager.GetString("TIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TINT           Brak przerwania.
        /// </summary>
        internal static string TINT {
            get {
                return ResourceManager.GetString("TINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLK            SHT, LK=0 || !SHT, LK!=0.
        /// </summary>
        internal static string TLK {
            get {
                return ResourceManager.GetString("TLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSD            ZNAK = 0.
        /// </summary>
        internal static string TSD {
            get {
                return ResourceManager.GetString("TSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXZ            BXZ i RI &lt;&gt; 0 || TLD i RI = 0.
        /// </summary>
        internal static string TXZ {
            get {
                return ResourceManager.GetString("TXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNB            Zawsze pozytywny.
        /// </summary>
        internal static string UNB {
            get {
                return ResourceManager.GetString("UNB", resourceCulture);
            }
        }
    }
}
