//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabZSK.StaticClasses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Operations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Operations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabZSK.StaticClasses.Operations", typeof(Operations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = LALU + RALU.
        /// </summary>
        internal static string ADS {
            get {
                return ResourceManager.GetString("ADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arytmetyczne A w lewo.
        /// </summary>
        internal static string ALA {
            get {
                return ResourceManager.GetString("ALA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = LALU AND RALU.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT A0 -&gt; MQ15.
        /// </summary>
        internal static string AQ15 {
            get {
                return ResourceManager.GetString("AQ15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arytmetyczne A w prawo.
        /// </summary>
        internal static string ARA {
            get {
                return ResourceManager.GetString("ARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz adres efektywny.
        /// </summary>
        internal static string CEA {
            get {
                return ResourceManager.GetString("CEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = (NOT LALU)+1.
        /// </summary>
        internal static string CMA {
            get {
                return ResourceManager.GetString("CMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = (NOT RALU)+1.
        /// </summary>
        internal static string CMX {
            get {
                return ResourceManager.GetString("CMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęcie CWC.
        /// </summary>
        internal static string CWC {
            get {
                return ResourceManager.GetString("CWC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = LALU - 1.
        /// </summary>
        internal static string DECL {
            get {
                return ResourceManager.GetString("DECL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = RALU - 1.
        /// </summary>
        internal static string DECR {
            get {
                return ResourceManager.GetString("DECR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 -&gt; LK.
        /// </summary>
        internal static string DIV {
            get {
                return ResourceManager.GetString("DIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LK = [LK]-1.
        /// </summary>
        internal static string DLK {
            get {
                return ResourceManager.GetString("DLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RI = RI-1.
        /// </summary>
        internal static string DRI {
            get {
                return ResourceManager.GetString("DRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec mikroprogramu.
        /// </summary>
        internal static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odblokuj przerwania.
        /// </summary>
        internal static string ENI {
            get {
                return ResourceManager.GetString("ENI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = LALU XOR RALU.
        /// </summary>
        internal static string EOR {
            get {
                return ResourceManager.GetString("EOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; A.
        /// </summary>
        internal static string IA {
            get {
                return ResourceManager.GetString("IA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A -&gt; LALU.
        /// </summary>
        internal static string IALU {
            get {
                return ResourceManager.GetString("IALU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A0 -&gt; ZNAK.
        /// </summary>
        internal static string IAS {
            get {
                return ResourceManager.GetString("IAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; RALU.
        /// </summary>
        internal static string IBE {
            get {
                return ResourceManager.GetString("IBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; RAE.
        /// </summary>
        internal static string IBI {
            get {
                return ResourceManager.GetString("IBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; LK.
        /// </summary>
        internal static string ILK {
            get {
                return ResourceManager.GetString("ILK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; LR.
        /// </summary>
        internal static string ILR {
            get {
                return ResourceManager.GetString("ILR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; MQ.
        /// </summary>
        internal static string IMQ {
            get {
                return ResourceManager.GetString("IMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = LALU + 1.
        /// </summary>
        internal static string INCL {
            get {
                return ResourceManager.GetString("INCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = RALU + 1.
        /// </summary>
        internal static string INCR {
            get {
                return ResourceManager.GetString("INCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMA -&gt; RAE.
        /// </summary>
        internal static string IRAE {
            get {
                return ResourceManager.GetString("IRAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; RAP.
        /// </summary>
        internal static string IRAP {
            get {
                return ResourceManager.GetString("IRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; RBP.
        /// </summary>
        internal static string IRBP {
            get {
                return ResourceManager.GetString("IRBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; RI.
        /// </summary>
        internal static string IRI {
            get {
                return ResourceManager.GetString("IRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; RR.
        /// </summary>
        internal static string IRR {
            get {
                return ResourceManager.GetString("IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęcie IWC.
        /// </summary>
        internal static string IWC {
            get {
                return ResourceManager.GetString("IWC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; X.
        /// </summary>
        internal static string IX {
            get {
                return ResourceManager.GetString("IX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RI -&gt; LALU.
        /// </summary>
        internal static string IXRE {
            get {
                return ResourceManager.GetString("IXRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = LALU.
        /// </summary>
        internal static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cykliczne A w lewo.
        /// </summary>
        internal static string LCA {
            get {
                return ResourceManager.GetString("LCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logiczne A w lewo.
        /// </summary>
        internal static string LLA {
            get {
                return ResourceManager.GetString("LLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logiczne A i MQ w lewo.
        /// </summary>
        internal static string LLQ {
            get {
                return ResourceManager.GetString("LLQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logiczne A w prawo.
        /// </summary>
        internal static string LRA {
            get {
                return ResourceManager.GetString("LRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logiczne A i MQ w prawo.
        /// </summary>
        internal static string LRQ {
            get {
                return ResourceManager.GetString("LRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 -&gt; LK.
        /// </summary>
        internal static string MUL {
            get {
                return ResourceManager.GetString("MUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = NOT LALU.
        /// </summary>
        internal static string NOTL {
            get {
                return ResourceManager.GetString("NOTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = NOT RALU.
        /// </summary>
        internal static string NOTR {
            get {
                return ResourceManager.GetString("NOTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR+1 -&gt; LR.
        /// </summary>
        internal static string NSI {
            get {
                return ResourceManager.GetString("NSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A -&gt; BUS.
        /// </summary>
        internal static string OA {
            get {
                return ResourceManager.GetString("OA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU -&gt; BUS.
        /// </summary>
        internal static string OBE {
            get {
                return ResourceManager.GetString("OBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR -&gt; BUS.
        /// </summary>
        internal static string OLR {
            get {
                return ResourceManager.GetString("OLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQ -&gt; BUS.
        /// </summary>
        internal static string OMQ {
            get {
                return ResourceManager.GetString("OMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = 1.
        /// </summary>
        internal static string ONE {
            get {
                return ResourceManager.GetString("ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP lub AOP+32 -&gt; RAPS.
        /// </summary>
        internal static string OPC {
            get {
                return ResourceManager.GetString("OPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = LALU OR RALU.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAE -&gt; BUS.
        /// </summary>
        internal static string ORAE {
            get {
                return ResourceManager.GetString("ORAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBP -&gt; BUS.
        /// </summary>
        internal static string ORBP {
            get {
                return ResourceManager.GetString("ORBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RI -&gt; BUS.
        /// </summary>
        internal static string ORI {
            get {
                return ResourceManager.GetString("ORI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RR -&gt; BUS.
        /// </summary>
        internal static string ORR {
            get {
                return ResourceManager.GetString("ORR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X -&gt; BUS.
        /// </summary>
        internal static string OX {
            get {
                return ResourceManager.GetString("OX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X -&gt; RALU.
        /// </summary>
        internal static string OXE {
            get {
                return ResourceManager.GetString("OXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = RALU.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A = 0.
        /// </summary>
        internal static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT = 0.
        /// </summary>
        internal static string RINT {
            get {
                return ResourceManager.GetString("RINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQ = 0.
        /// </summary>
        internal static string RMQ {
            get {
                return ResourceManager.GetString("RMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF = 0.
        /// </summary>
        internal static string ROFF {
            get {
                return ResourceManager.GetString("ROFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęcie RRC.
        /// </summary>
        internal static string RRC {
            get {
                return ResourceManager.GetString("RRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRO = 0.
        /// </summary>
        internal static string RXRO {
            get {
                return ResourceManager.GetString("RXRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X0 -&gt; ZNAK.
        /// </summary>
        internal static string SGN {
            get {
                return ResourceManager.GetString("SGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja przesunięcia.
        /// </summary>
        internal static string SHT {
            get {
                return ResourceManager.GetString("SHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF = 1.
        /// </summary>
        internal static string SOFF {
            get {
                return ResourceManager.GetString("SOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUS -&gt; RBP.
        /// </summary>
        internal static string SRBP {
            get {
                return ResourceManager.GetString("SRBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = LALU - RALU.
        /// </summary>
        internal static string SUS {
            get {
                return ResourceManager.GetString("SUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRO = 1.
        /// </summary>
        internal static string SXRO {
            get {
                return ResourceManager.GetString("SXRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF = 0.
        /// </summary>
        internal static string TAO {
            get {
                return ResourceManager.GetString("TAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt; 0.
        /// </summary>
        internal static string TAP {
            get {
                return ResourceManager.GetString("TAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &gt;= 0.
        /// </summary>
        internal static string TAS {
            get {
                return ResourceManager.GetString("TAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A = 0.
        /// </summary>
        internal static string TAZ {
            get {
                return ResourceManager.GetString("TAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresowanie pośrednie.
        /// </summary>
        internal static string TIND {
            get {
                return ResourceManager.GetString("TIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak przerwania.
        /// </summary>
        internal static string TINT {
            get {
                return ResourceManager.GetString("TINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHT, LK=0 || !SHT, LK!=0.
        /// </summary>
        internal static string TLK {
            get {
                return ResourceManager.GetString("TLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQ15 = 0.
        /// </summary>
        internal static string TQ15 {
            get {
                return ResourceManager.GetString("TQ15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZNAK = 0.
        /// </summary>
        internal static string TSD {
            get {
                return ResourceManager.GetString("TSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RI &lt; 0.
        /// </summary>
        internal static string TXP {
            get {
                return ResourceManager.GetString("TXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XRO = 0.
        /// </summary>
        internal static string TXRO {
            get {
                return ResourceManager.GetString("TXRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RI &gt;= 0.
        /// </summary>
        internal static string TXS {
            get {
                return ResourceManager.GetString("TXS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BXZ i RI &lt;&gt; 0 || TLD i RI = 0.
        /// </summary>
        internal static string TXZ {
            get {
                return ResourceManager.GetString("TXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawsze pozytywny.
        /// </summary>
        internal static string UNB {
            get {
                return ResourceManager.GetString("UNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALU = 0.
        /// </summary>
        internal static string ZERO {
            get {
                return ResourceManager.GetString("ZERO", resourceCulture);
            }
        }
    }
}
