//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabZSK.Other {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabZSK.Other.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor programu: Konrad Tomasz Ziarko.
        /// </summary>
        internal static string authorName {
            get {
                return ResourceManager.GetString("authorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie LabZSK.
        /// </summary>
        internal static string AuthorTitle {
            get {
                return ResourceManager.GetString("AuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opóźnienie trybu auto(ms):.
        /// </summary>
        internal static string autoModeLatencyLabel {
            get {
                return ResourceManager.GetString("autoModeLatencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połącz.
        /// </summary>
        internal static string connectButton {
            get {
                return ResourceManager.GetString("connectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsola deweloperska.
        /// </summary>
        internal static string devConsoleLabel {
            get {
                return ResourceManager.GetString("devConsoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progi ocen:.
        /// </summary>
        internal static string gradingScaleLabel {
            get {
                return ResourceManager.GetString("gradingScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupa.
        /// </summary>
        internal static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string groupBoxName {
            get {
                return ResourceManager.GetString("groupBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydział Cybernetyki
        ///Instytut Teleinformatyki i Automatyki.
        /// </summary>
        internal static string instituteName {
            get {
                return ResourceManager.GetString("instituteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres serwera.
        /// </summary>
        internal static string ipAddress {
            get {
                return ResourceManager.GetString("ipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język:.
        /// </summary>
        internal static string languageLabel {
            get {
                return ResourceManager.GetString("languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj konfigurację.
        /// </summary>
        internal static string loadConfigButton {
            get {
                return ResourceManager.GetString("loadConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamykanie logu.
        /// </summary>
        internal static string logClosing {
            get {
                return ResourceManager.GetString("logClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imie.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje.
        /// </summary>
        internal static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierownik: dr inż. Witold Żorski.
        /// </summary>
        internal static string promoterName {
            get {
                return ResourceManager.GetString("promoterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz konfigurację.
        /// </summary>
        internal static string saveConfigButton {
            get {
                return ResourceManager.GetString("saveConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwer.
        /// </summary>
        internal static string serverTitle {
            get {
                return ResourceManager.GetString("serverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domyślna.
        /// </summary>
        internal static string themeComboBox1 {
            get {
                return ResourceManager.GetString("themeComboBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niebieska.
        /// </summary>
        internal static string themeComboBox2 {
            get {
                return ResourceManager.GetString("themeComboBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czerwona.
        /// </summary>
        internal static string themeComboBox3 {
            get {
                return ResourceManager.GetString("themeComboBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czarna.
        /// </summary>
        internal static string themeComboBox4 {
            get {
                return ResourceManager.GetString("themeComboBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skórka:.
        /// </summary>
        internal static string themeLabel {
            get {
                return ResourceManager.GetString("themeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsultant: mgr inż. Artur Miktus.
        /// </summary>
        internal static string theOtherGuy {
            get {
                return ResourceManager.GetString("theOtherGuy", resourceCulture);
            }
        }
    }
}
