//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabZSK.MicroOperations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabZSK.MicroOperations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy napewno chcesz wyczyścić całą pamięć?.
        /// </summary>
        internal static string areYouSureClearTable {
            get {
                return ResourceManager.GetString("areYouSureClearTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tej operacji nie da się cofnąć!.
        /// </summary>
        internal static string areYouSureClearTableTitle {
            get {
                return ResourceManager.GetString("areYouSureClearTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string cellAddressViewGrid {
            get {
                return ResourceManager.GetString("cellAddressViewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść wiersz.
        /// </summary>
        internal static string clearRowButton {
            get {
                return ResourceManager.GetString("clearRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść pamięć.
        /// </summary>
        internal static string clearTableButton {
            get {
                return ResourceManager.GetString("clearTableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj komórkę.
        /// </summary>
        internal static string editMemoryButton {
            get {
                return ResourceManager.GetString("editMemoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykryto niespójność pliku!.
        /// </summary>
        internal static string inconsistentMicrocodeFile {
            get {
                return ResourceManager.GetString("inconsistentMicrocodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj pamięć.
        /// </summary>
        internal static string loadTableButton {
            get {
                return ResourceManager.GetString("loadTableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To nie jest plik z poprawnym mikroprogramem!.
        /// </summary>
        internal static string notValidMicrocodeFile {
            get {
                return ResourceManager.GetString("notValidMicrocodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładowanie mikroprogramu przerwane.
        /// </summary>
        internal static string notValidMicrocodeFileTitle {
            get {
                return ResourceManager.GetString("notValidMicrocodeFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamięć Mikroprogramów.
        /// </summary>
        internal static string PMViewTitle {
            get {
                return ResourceManager.GetString("PMViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz pamięć.
        /// </summary>
        internal static string saveTableButton {
            get {
                return ResourceManager.GetString("saveTableButton", resourceCulture);
            }
        }
    }
}
