//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabZSK.Simulation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabZSK.Simulation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystko.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja jest już uruchomina!.
        /// </summary>
        internal static string appAlreadyRunning {
            get {
                return ResourceManager.GetString("appAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz zakończyć pracę z obecnym logiem?.
        /// </summary>
        internal static string areYouSureCloseLog {
            get {
                return ResourceManager.GetString("areYouSureCloseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa symulacja.
        /// </summary>
        internal static string areYouSureCloseLogTitle {
            get {
                return ResourceManager.GetString("areYouSureCloseLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy napewno chcesz zakończyć pracę?
        ///Log symulacji zostanie zamknięty..
        /// </summary>
        internal static string areYouSureExit {
            get {
                return ResourceManager.GetString("areYouSureExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przerwanie pracy.
        /// </summary>
        internal static string areYouSureExitTitle {
            get {
                return ResourceManager.GetString("areYouSureExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie LabZSK.
        /// </summary>
        internal static string authorToolStrip {
            get {
                return ResourceManager.GetString("authorToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja ustawień dozwolona!.
        /// </summary>
        internal static string canEditSettings {
            get {
                return ResourceManager.GetString("canEditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie posiadasz uprawnień do wykonania tej operacji.
        /// </summary>
        internal static string cantCloseLogFile {
            get {
                return ResourceManager.GetString("cantCloseLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string cellAddressViewGrid {
            get {
                return ResourceManager.GetString("cellAddressViewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawartość.
        /// </summary>
        internal static string cellValueViewGrid {
            get {
                return ResourceManager.GetString("cellValueViewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ====Zerowanie rejestrów====.
        /// </summary>
        internal static string clearingRegister {
            get {
                return ResourceManager.GetString("clearingRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeruj rejestry.
        /// </summary>
        internal static string clearRegistersToolStrip {
            get {
                return ResourceManager.GetString("clearRegistersToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij log.
        /// </summary>
        internal static string closeLogToolStrip {
            get {
                return ResourceManager.GetString("closeLogToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprawna.
        /// </summary>
        internal static string correct {
            get {
                return ResourceManager.GetString("correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz log.
        /// </summary>
        internal static string createLog {
            get {
                return ResourceManager.GetString("createLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cykl.
        /// </summary>
        internal static string cycle {
            get {
                return ResourceManager.GetString("cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANA.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja wykorzystuje Moje Dokumenty/Dokumenty jako domyślny katalog dla plików!.
        /// </summary>
        internal static string defaultDirectoryMessage {
            get {
                return ResourceManager.GetString("defaultDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsola deweloperska....
        /// </summary>
        internal static string devConsoleToolStrip {
            get {
                return ResourceManager.GetString("devConsoleToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string editMemToolStrip {
            get {
                return ResourceManager.GetString("editMemToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja.
        /// </summary>
        internal static string editMode {
            get {
                return ResourceManager.GetString("editMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string editPMToolStrip {
            get {
                return ResourceManager.GetString("editPMToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj rejestry.
        /// </summary>
        internal static string editRegisters {
            get {
                return ResourceManager.GetString("editRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ edycję.
        /// </summary>
        internal static string endEditRegisters {
            get {
                return ResourceManager.GetString("endEditRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd podczas tworzenia logu!.
        /// </summary>
        internal static string errorLogCreating {
            get {
                return ResourceManager.GetString("errorLogCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ pracę.
        /// </summary>
        internal static string exitToolStrip {
            get {
                return ResourceManager.GetString("exitToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj....
        /// </summary>
        internal static string loadMemToolStrip {
            get {
                return ResourceManager.GetString("loadMemToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj....
        /// </summary>
        internal static string loadPMToolStrip {
            get {
                return ResourceManager.GetString("loadPMToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Można zamykać log.
        /// </summary>
        internal static string logClosingAllowed {
            get {
                return ResourceManager.GetString("logClosingAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konieczne jest utworzenie pliku LOG.
        /// </summary>
        internal static string logFileName {
            get {
                return ResourceManager.GetString("logFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalogowano jako.
        /// </summary>
        internal static string loggedAs {
            get {
                return ResourceManager.GetString("loggedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log pracy programu jest niespójny.
        /// </summary>
        internal static string logInconsistent {
            get {
                return ResourceManager.GetString("logInconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log został zmodyfikowany w trakcie pracy.
        /// </summary>
        internal static string logModified {
            get {
                return ResourceManager.GetString("logModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacja.
        /// </summary>
        internal static string machineName {
            get {
                return ResourceManager.GetString("machineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena.
        /// </summary>
        internal static string mark {
            get {
                return ResourceManager.GetString("mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana zawartości pamięci operacyjnej:.
        /// </summary>
        internal static string memHasChanged {
            get {
                return ResourceManager.GetString("memHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamięć operacyjna.
        /// </summary>
        internal static string memToolStrip {
            get {
                return ResourceManager.GetString("memToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikro.
        /// </summary>
        internal static string micro {
            get {
                return ResourceManager.GetString("micro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana zawartości pamięci mikroprogramów:.
        /// </summary>
        internal static string microcodeHasChanged {
            get {
                return ResourceManager.GetString("microcodeHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikroprogramy.
        /// </summary>
        internal static string microToolStrip {
            get {
                return ResourceManager.GetString("microToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string mistake {
            get {
                return ResourceManager.GetString("mistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędy.
        /// </summary>
        internal static string mistakes {
            get {
                return ResourceManager.GetString("mistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne interfejsy sieciowe.
        /// </summary>
        internal static string networkInterfaces {
            get {
                return ResourceManager.GetString("networkInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następny takt.
        /// </summary>
        internal static string nextTactButton {
            get {
                return ResourceManager.GetString("nextTactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja nie jest w trybie dla studenta!.
        /// </summary>
        internal static string notForStudents {
            get {
                return ResourceManager.GetString("notForStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        internal static string okButton {
            get {
                return ResourceManager.GetString("okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komputer w domenie.
        /// </summary>
        internal static string pcInDomain {
            get {
                return ResourceManager.GetString("pcInDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start symulatora.
        /// </summary>
        internal static string programStart {
            get {
                return ResourceManager.GetString("programStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana zawartości rejestru:.
        /// </summary>
        internal static string registerHasChanged {
            get {
                return ResourceManager.GetString("registerHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ======Zawartość rejestrów======.
        /// </summary>
        internal static string registersContent {
            get {
                return ResourceManager.GetString("registersContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcje....
        /// </summary>
        internal static string settingsToolStrip {
            get {
                return ResourceManager.GetString("settingsToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż log.
        /// </summary>
        internal static string showLogButton {
            get {
                return ResourceManager.GetString("showLogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż log....
        /// </summary>
        internal static string showLogToolStrip {
            get {
                return ResourceManager.GetString("showLogToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZNAK.
        /// </summary>
        internal static string sign {
            get {
                return ResourceManager.GetString("sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log symulatora.
        /// </summary>
        internal static string simLog {
            get {
                return ResourceManager.GetString("simLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ======Stop  symulacji======.
        /// </summary>
        internal static string simStop {
            get {
                return ResourceManager.GetString("simStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==Symulacja przerwana==.
        /// </summary>
        internal static string simulationBreak {
            get {
                return ResourceManager.GetString("simulationBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komputer LabZSK.
        /// </summary>
        internal static string SimulationTitle {
            get {
                return ResourceManager.GetString("SimulationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symulacja.
        /// </summary>
        internal static string simulationToolStrip {
            get {
                return ResourceManager.GetString("simulationToolStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ======Start symulacji======.
        /// </summary>
        internal static string startingSimulation {
            get {
                return ResourceManager.GetString("startingSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string startMode {
            get {
                return ResourceManager.GetString("startMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stopMode {
            get {
                return ResourceManager.GetString("stopMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takt.
        /// </summary>
        internal static string tact {
            get {
                return ResourceManager.GetString("tact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd logu.
        /// </summary>
        internal static string viewLogFile {
            get {
                return ResourceManager.GetString("viewLogFile", resourceCulture);
            }
        }
    }
}
